"""Two balls from one: the paradox lives in a group, and choice moves it to the sphere.

Hausdorff (1914), Banach and Tarski (1924) and Robinson (1947) showed that a
ball can be cut into finitely many pieces that reassemble, by rotations and
translations alone, into two balls the size of the original. The pieces are
not shapes; they are sets, chosen with the axiom of choice. The program shows
the three parts of the construction that a program can check exactly: a group
that doubles itself, a pair of rotations whose group is that free, and the
labelling of the group's Cayley graph that Halbeisen's chapter 7 draws. The
last step, carrying the labels from the group onto the points of the sphere,
is the axiom of choice, and the program says exactly where it is used.
Everything uses the standard library only.
"""

from fractions import Fraction
from itertools import product

# ---------------------------------------------------------------------------
# 1. The free group on two letters: reduced words, with inverses as capitals
# ---------------------------------------------------------------------------

INV = {"a": "A", "A": "a", "b": "B", "B": "b"}


def reduce_word(w):
    out = []
    for ch in w:
        if out and out[-1] == INV[ch]:
            out.pop()
        else:
            out.append(ch)
    return "".join(out)


def free_words(max_len):
    """All reduced words of length <= max_len, as strings."""
    words = {""}
    frontier = {""}
    for _ in range(max_len):
        nxt = set()
        for w in frontier:
            for ch in "aAbB":
                if not w or w[-1] != INV[ch]:
                    nxt.add(w + ch)
        words |= nxt
        frontier = nxt
    return words


# ---------------------------------------------------------------------------
# 2. Exact arithmetic in Q(√3): a number is p + q√3 with p, q fractions
# ---------------------------------------------------------------------------


def num(p, q=0):
    return (Fraction(p), Fraction(q))


def add(x, y):
    return (x[0] + y[0], x[1] + y[1])


def mul(x, y):
    return (x[0] * y[0] + 3 * x[1] * y[1], x[0] * y[1] + x[1] * y[0])


def matmul(M, N):
    return tuple(
        tuple(
            add(add(mul(M[i][0], N[0][j]), mul(M[i][1], N[1][j])), mul(M[i][2], N[2][j]))
            for j in range(3)
        )
        for i in range(3)
    )


IDENTITY = tuple(tuple(num(1 if i == j else 0) for j in range(3)) for i in range(3))
H = Fraction(1, 2)
PHI = ((num(0), num(0), num(1)), (num(0), num(-1), num(0)), (num(1), num(0), num(0)))
PSI = ((num(-H), num(0, -H), num(0)), (num(0, H), num(-H), num(0)), (num(0), num(0), num(1)))
PSI_INV = ((num(-H), num(0, H), num(0)), (num(0, -H), num(-H), num(0)), (num(0), num(0), num(1)))
LETTER = {"f": PHI, "p": PSI, "q": PSI_INV}


def show(x):
    p, q = x
    parts = []
    if p or not q:
        parts.append(str(p))
    if q:
        parts.append(f"{q}√3" if q != 1 else "√3")
    return "+".join(parts).replace("+-", "-")


# ---------------------------------------------------------------------------
# 3. Reduced words in the group generated by φ and ψ, with φ² = ψ³ = ι
# ---------------------------------------------------------------------------

PSI_TYPE = {"p", "q"}


def left_mult(letter, w):
    """Reduced form of letter·w, for w a reduced word in f (φ), p (ψ), q (ψ⁻¹)."""
    if not w:
        return letter
    head = w[0]
    if letter == "f":
        return w[1:] if head == "f" else "f" + w
    if head == "f":
        return letter + w
    # both are ψ-type: p·p = q, q·q = p, p·q = q·p = ι
    if letter == head:
        return ("q" if letter == "p" else "p") + w[1:]
    return w[1:]


def rotation_words(max_len):
    words = {""}
    frontier = {""}
    for _ in range(max_len):
        nxt = set()
        for w in frontier:
            for letter in "fpq":
                v = left_mult(letter, w)
                if len(v) == len(w) + 1:
                    nxt.add(v)
        words |= nxt
        frontier = nxt
    return words


def matrix_of(w):
    M = IDENTITY
    for letter in w:
        M = matmul(M, LETTER[letter])
    return M


NEXT = {1: 2, 2: 3, 3: 1}
PREV = {1: 3, 2: 1, 3: 2}


def label(w):
    """Halbeisen's labelling of the Cayley graph, by recursion on the reduced word."""
    if not w:
        return 1
    rest = label(w[1:])
    if w[0] == "p":
        return NEXT[rest]
    if w[0] == "q":
        return PREV[rest]
    return 1 if rest in (2, 3) else 2


def main():
    print("1. A GROUP THAT DOUBLES ITSELF: THE FREE GROUP ON a AND b")
    L = 7
    ball = free_words(L)
    inner = {w for w in ball if len(w) <= L - 1}
    S = {ch: {w for w in ball if w and w[0] == ch} for ch in "aAbB"}
    print(f"   reduced words in a, b and their inverses A, B, of length ≤ {L}: {len(ball)}")
    print("   split them by first letter: S(a), S(A), S(b), S(B), and the empty word")
    print("   " + ", ".join(f"|S({ch})| = {len(S[ch])}" for ch in "aAbB"))
    a_SA = {reduce_word("a" + w) for w in S["A"]}
    b_SB = {reduce_word("b" + w) for w in S["B"]}
    claim1 = all(w in S["a"] or w in a_SA for w in inner) and not (S["a"] & a_SA)
    claim2 = all(w in S["b"] or w in b_SB for w in inner) and not (S["b"] & b_SB)
    print(f"   every word (length ≤ {L - 1}) is in S(a) or in a·S(A), never both: {claim1}")
    print(f"   every word (length ≤ {L - 1}) is in S(b) or in b·S(B), never both: {claim2}")
    print("   So the group is S(a) ⊔ a·S(A) and also S(b) ⊔ b·S(B): four pieces,")
    print("   two of them moved by one letter, make two copies of the whole group.")
    print("   (The empty word is the one leftover; a trick absorbs it.) A measure that")
    print("   is finitely additive and invariant under left multiplication cannot exist.")
    print()

    print("2. HAUSDORFF'S TWO ROTATIONS GENERATE A GROUP THAT IS JUST AS FREE")
    print("   φ: half turn about the axis (1, 0, 1);  ψ: third turn about the z-axis")
    print(f"   φ² = ι: {matmul(PHI, PHI) == IDENTITY};   ψ³ = ι: {matmul(matmul(PSI, PSI), PSI) == IDENTITY};"
          f"   ψ·ψ⁻¹ = ι: {matmul(PSI, PSI_INV) == IDENTITY}")
    N = 12
    words = rotation_words(N)
    mats = {w: matrix_of(w) for w in words}
    distinct = len(set(mats.values()))
    non_identity = sum(1 for w, M in mats.items() if w and M == IDENTITY)
    print(f"   reduced words in φ, ψ, ψ⁻¹ of length ≤ {N} (φ² = ψ³ = ι used to reduce): {len(words)}")
    print(f"   distinct rotation matrices among them: {distinct};  non-empty words equal to ι: {non_identity}")
    print("   Exact arithmetic in p + q√3, so 'distinct' is exact, not a float comparison.")
    print("   Halbeisen (p. 175) states the shape of 2ⁿ·(ψ^±φ ⋯ ψ^±φ): the entries marked")
    print("   a are even integers, those marked b are odd integers times √3 or not:")
    print("        ⎛ a₁    b₁√3  b₂  ⎞")
    print("        ⎜ a₂√3  b₃    b₄√3 ⎟")
    print("        ⎝ a₃    a₄√3  a₅  ⎠")
    sqrt_positions = {(0, 1), (1, 0), (1, 2), (2, 1)}
    odd_positions = {(0, 1), (0, 2), (1, 1), (1, 2)}
    checked = bad = 0
    for n in range(1, 9):
        for signs in product("pq", repeat=n):
            w = "".join(s + "f" for s in signs)
            M = matrix_of(w)
            checked += 1
            for i in range(3):
                for j in range(3):
                    p, q = M[i][j]
                    p, q = p * 2 ** n, q * 2 ** n
                    rational_part, root_part = p, q
                    if (i, j) in sqrt_positions:
                        value, zero = root_part, rational_part
                    else:
                        value, zero = rational_part, root_part
                    want_odd = (i, j) in odd_positions
                    if zero != 0 or value.denominator != 1 or (value.numerator % 2 == 1) != want_odd:
                        bad += 1
    print(f"   products of n ≤ 8 factors ψ^±φ checked: {checked};  entries breaking the pattern: {bad}")
    print("   The pattern shows no such product is ι (ι has odd entries where a's sit),")
    print("   so the only relations are φ² = ψ³ = ι, and the group is the free product")
    print("   ℤ₂ * ℤ₃. It contains a free group on two letters, so section 1 applies.")
    print()

    print("3. THE LABELLED CAYLEY GRAPH: THREE PIECES, ONE A THIRD AND ALSO A HALF")
    print("   Halbeisen's rules: ι gets ❶; φ sends ❷ or ❸ to ❶ and ❶ to ❷ (or ❸);")
    print("   ψ sends ❶ → ❷ → ❸ → ❶. Labels by recursion on the reduced word:")
    for w in ["", "f", "p", "q", "fp", "pf", "qf", "fpf", "pfp", "fqf"]:
        print(f"      {w or 'ι':<5} → ❶❷❸"[0:0] + f"      {(w or 'ι'):<5} label {label(w)}")
    R = 10
    ball = rotation_words(R)
    lab = {w: label(w) for w in ball}
    edges = 0
    broken = 0
    for w in ball:
        if len(w) >= R:
            continue
        for letter in "fp":
            v = left_mult(letter, w)
            edges += 1
            if letter == "f":
                ok = (lab[v] == 1) if lab[w] in (2, 3) else (lab[v] in (2, 3))
            else:
                ok = lab[v] == NEXT[lab[w]]
            broken += not ok
    print(f"   Cayley-graph edges checked in the ball of radius {R}: {edges};  rules broken: {broken}")
    A = {w for w in ball if lab[w] == 1}
    B = {w for w in ball if lab[w] == 2}
    C = {w for w in ball if lab[w] == 3}
    inner = {w for w in ball if len(w) < R}
    psiA = {left_mult("p", w) for w in A}
    psi_invA = {left_mult("q", w) for w in A}
    phiA = {left_mult("f", w) for w in A}
    print(f"   |A| = {len(A)}, |B| = {len(B)}, |C| = {len(C)} in the ball")
    print(f"   B = ψ[A]:      {B & inner == psiA & inner}")
    print(f"   C = ψ⁻¹[A]:    {C & inner == psi_invA & inner}")
    print(f"   B ∪ C = φ[A]:  {(B | C) & inner == phiA & inner}")
    print("   (each identity checked on the words that stay inside the ball)")
    print("   So A ≅ B, A ≅ C and A ≅ B ∪ C: the piece A is a third of the group and,")
    print("   rotated by φ, also two thirds of it. Nothing here used the axiom of choice.")
    print()

    print("4. WHERE THE AXIOM OF CHOICE ENTERS, AND WHAT IT COSTS")
    print("   The group acts on the sphere. Two points are equivalent when some rotation")
    print("   in the group moves one to the other; the classes are the orbits. Choose")
    print("   one point in every orbit (the axiom of choice: uncountably many orbits,")
    print("   no rule). Every other point x is ρ(chosen point) for exactly one ρ in the")
    print("   group, and x gets ρ's label. The sphere, minus the countable set F of")
    print("   points on some rotation axis, becomes A ⊔ B ⊔ C with B = ψ[A],")
    print("   C = ψ⁻¹[A], B ∪ C = φ[A]: Hausdorff's paradox (1914).")
    print("   A volume μ that is additive on disjoint sets and equal on congruent sets:")
    print("     μ(A) = μ(B) = μ(C)            congruent pieces")
    print("     μ(A) = μ(B ∪ C) = μ(B) + μ(C)  congruent, then additive")
    print("     so μ(A) = 2·μ(A), μ(A) = 0, and μ(sphere ∖ F) = 3·μ(A) = 0,")
    print("     against μ(sphere) > 0 with F countable. No such μ exists on all subsets.")
    print("   Robinson (1947): the solid ball is five pieces that make two balls, and four")
    print("   do not suffice; Banach and Tarski (1924) had it with more pieces. Without")
    print("   the axiom of choice neither decomposition can be proved (Halbeisen's Related")
    print("   Result 48): in Solovay's model every set of reals has a volume.")


if __name__ == "__main__":
    main()
